# prompt
fpath+=("$(brew --prefix)/share/zsh/site-functions")
autoload -U promptinit; promptinit
prompt pure

# autocompletion
autoload -U compinit; compinit

# remove duplicates from path
typeset -U path

# !! Contents within this block are managed by juliaup !!
path=("$HOME/.juliaup/bin" $path)
# <<< juliaup initialize <<<

export PYENV_ROOT="$HOME/.pyenv"
[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init - zsh)"
